# Official Real Government Schemes Dataset
# Sourced from National Portal of India (india.gov.in), myScheme.gov.in, data.gov.in, and official Central/State Ministry Portals.

REAL_GOVT_SCHEMES = [
    # 1. PM-KISAN
    {
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "short_name": "PM-KISAN",
        "short_description": "Direct income support of ₹6,000 per year in three equal installments to all landholding farmer families across India.",
        "full_description": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) is a Central Sector Scheme funded 100% by the Government of India. Under the scheme, income support of ₹6,000/- per year in three equal installments of ₹2,000/- each is provided to all landholding farmer families.",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "department": "Department of Agriculture and Farmers Welfare",
        "category": "Farmers",
        "sub_category": "Income Support",
        "benefit": "₹6,000 / year direct bank transfer (DBT)",
        "benefit_amount": "₹6,000",
        "launch_year": 2019,
        "status": "Active",
        "target_beneficiaries": "Landholding Farmer Families",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 120,
        "max_income": 1000000.0,
        "occupation_rules": ["Farmer"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": ["farmer"],
        "documents": ["Aadhaar Card", "Land Holding Ownership Document (Khasra/Khatauni)", "Active Bank Account linked with Aadhaar"],
        "application_steps": ["Visit PM-KISAN official portal (pmkisan.gov.in)", "Click on 'New Farmer Registration'", "Enter Aadhaar Number and State", "Fill land and bank details and submit"],
        "official_source_url": "https://pmkisan.gov.in/",
        "official_application_url": "https://pmkisan.gov.in/RegistrationFormNew.aspx",
        "source_name": "Ministry of Agriculture & Farmers Welfare / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 2. Ayushman Bharat PM-JAY
    {
        "name": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        "short_name": "PM-JAY",
        "short_description": "Health cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalization to over 12 crore poor families.",
        "full_description": "Ayushman Bharat PM-JAY is the world's largest health insurance/assurance scheme fully financed by the government. It provides a cover of ₹5 lakhs per family per year for secondary and tertiary care hospitalization across public and private empanelled hospitals in India.",
        "state": "All India",
        "scheme_type": "Centrally Sponsored",
        "government_level": "Central",
        "ministry": "Ministry of Health and Family Welfare",
        "department": "National Health Authority (NHA)",
        "category": "Health",
        "sub_category": "Health Insurance",
        "benefit": "₹5,000,000 cashless health insurance cover per family / year",
        "benefit_amount": "₹500,000",
        "launch_year": 2018,
        "status": "Active",
        "target_beneficiaries": "Poor and vulnerable families identified under SECC 2011",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 0,
        "max_age": 120,
        "max_income": 300000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": ["bpl"],
        "documents": ["Aadhaar Card / Ration Card", "Ration Card or SECC Household Verification"],
        "application_steps": ["Check eligibility on pmjay.gov.in or visit nearest Ayushman Kendra", "Verify Aadhaar e-KYC", "Receive Ayushman Golden Card"],
        "official_source_url": "https://pmjay.gov.in/",
        "official_application_url": "https://beneficiary.nha.gov.in/",
        "source_name": "National Health Authority / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 3. PM Awas Yojana (Gramin & Urban)
    {
        "name": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        "short_name": "PMAY-G",
        "short_description": "Financial assistance of ₹1.20 Lakh (Plains) to ₹1.30 Lakh (Hilly/Difficult areas) for construction of pucca house for rural homeless.",
        "full_description": "Pradhan Mantri Awas Yojana - Gramin aims to provide a pucca house with basic amenities to all houseless households and those living in kutcha and dilapidated houses in rural areas.",
        "state": "All India",
        "scheme_type": "Centrally Sponsored",
        "government_level": "Central",
        "ministry": "Ministry of Rural Development",
        "department": "Department of Rural Development",
        "category": "Housing",
        "sub_category": "Rural Housing",
        "benefit": "₹1,20,000 to ₹1,30,000 housing subsidy + 90 days MGNREGA labor wage",
        "benefit_amount": "₹130,000",
        "launch_year": 2016,
        "status": "Active",
        "target_beneficiaries": "Rural homeless households & kutcha house dwellers",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 120,
        "max_income": 300000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": ["bpl", "rural_resident"],
        "documents": ["Aadhaar Card", "Bank Account Details", "Job Card Number", "Swachh Bharat Mission (SBM) Registration Number"],
        "application_steps": ["Gram Sabha identifies eligible households based on SECC 2011 data", "Block Development Officer registers application on AwaasSoft portal", "Geo-tagging of construction site"],
        "official_source_url": "https://pmayg.nic.in/",
        "official_application_url": "https://pmayg.nic.in/netiay/Home.aspx",
        "source_name": "Ministry of Rural Development / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 4. Post-Matric Scholarship for SC Students
    {
        "name": "Post-Matric Scholarship for SC Students",
        "short_name": "PMS-SC",
        "short_description": "Financial assistance including maintenance allowance and non-refundable fees for Scheduled Caste students pursuing post-matriculation studies.",
        "full_description": "Post-Matric Scholarship for Scheduled Caste Students is a Centrally Sponsored Scheme to provide financial assistance to Scheduled Caste students studying at post-matriculation or post-secondary stage to enable them to complete their education.",
        "state": "All India",
        "scheme_type": "Centrally Sponsored",
        "government_level": "Central",
        "ministry": "Ministry of Social Justice and Empowerment",
        "department": "Department of Social Justice and Empowerment",
        "category": "Students",
        "sub_category": "Scholarships",
        "benefit": "Full tuition fee reimbursement + annual maintenance allowance up to ₹13,500",
        "benefit_amount": "Tuition Fee + Allowance",
        "launch_year": 2006,
        "status": "Active",
        "target_beneficiaries": "SC Category Students in Class 11, 12, Diploma, UG, PG",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 14,
        "max_age": 35,
        "max_income": 250000.0,
        "occupation_rules": ["Student"],
        "category_rules": ["SC"],
        "gender_rules": ["Any"],
        "special_conditions": ["student"],
        "documents": ["Aadhaar Card", "SC Caste Certificate", "Income Certificate (Annual income <= ₹2.5 Lakh)", "Class 10th / Previous Marksheet", "Fee Receipt & Bank Passbook"],
        "application_steps": ["Register on National Scholarship Portal (scholarships.gov.in)", "Fill academic and caste details", "Upload scanned certificates", "Institute verifies online"],
        "official_source_url": "https://scholarships.gov.in/",
        "official_application_url": "https://scholarships.gov.in/fresh/newNspLanding",
        "source_name": "National Scholarship Portal / Ministry of Social Justice",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 5. Atal Pension Yojana (APY)
    {
        "name": "Atal Pension Yojana (APY)",
        "short_name": "APY",
        "short_description": "Guaranteed monthly pension of ₹1,000 to ₹5,000 per month from age 60 for unorganized sector workers.",
        "full_description": "Atal Pension Yojana is a government-backed pension scheme in India targeted at the unorganized sector. Under the APY, guaranteed minimum pension of ₹1,000/-, ₹2,000/-, ₹3,000/-, ₹4,000/- or ₹5,000/- per month will be given at the age of 60 years depending on the contributions made.",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Finance",
        "department": "Pension Fund Regulatory and Development Authority (PFRDA)",
        "category": "Pension",
        "sub_category": "Social Security Pension",
        "benefit": "Guaranteed lifetime monthly pension of ₹1,000 to ₹5,000",
        "benefit_amount": "₹5,000 / month",
        "launch_year": 2015,
        "status": "Active",
        "target_beneficiaries": "Unorganized sector workers aged 18 to 40 years",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 40,
        "max_income": 10000000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": [],
        "documents": ["Aadhaar Card", "Active Savings Bank Account with auto-debit facility", "Mobile Number"],
        "application_steps": ["Visit your bank branch or net banking portal", "Fill APY registration form", "Setup monthly auto-debit contribution"],
        "official_source_url": "https://www.pfrda.org.in/",
        "official_application_url": "https://npslite-nsdl.com/CRALite/apySubscription.do",
        "source_name": "PFRDA / Ministry of Finance",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 6. PM MUDRA Yojana
    {
        "name": "Pradhan Mantri MUDRA Yojana (PMMY)",
        "short_name": "PMMY",
        "short_description": "Collateral-free business loans up to ₹10 Lakh for non-farm micro and small enterprises under Shishu, Kishore, and Tarun categories.",
        "full_description": "Pradhan Mantri MUDRA Yojana provides collateral-free loans up to ₹10 Lakhs to non-corporate, non-farm small/micro enterprises. Loans are given under three categories: Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 Lakh), and Tarun (₹5 Lakh to ₹10 Lakh).",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Finance",
        "department": "Department of Financial Services",
        "category": "Business",
        "sub_category": "Micro Credit Loans",
        "benefit": "Collateral-free institutional loan up to ₹10,00,000",
        "benefit_amount": "₹1,000,000",
        "launch_year": 2015,
        "status": "Active",
        "target_beneficiaries": "Micro entrepreneurs, shopkeepers, artisans, small business owners",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 65,
        "max_income": 10000000.0,
        "occupation_rules": ["Self Employed", "Street Vendor", "Artisan", "Other"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": ["entrepreneur"],
        "documents": ["Identity Proof (Aadhaar/Voter ID)", "Business Address & Ownership Proof", "Project Proposal / Quotation for machinery", "Bank Statement (Last 6 months)"],
        "application_steps": ["Apply online via JanSamarth portal (jansamarth.in)", "Select MUDRA category", "Upload business plan and bank statement", "Bank evaluates and disburses loan"],
        "official_source_url": "https://www.mudra.org.in/",
        "official_application_url": "https://www.jansamarth.in/home",
        "source_name": "MUDRA Ltd / JanSamarth Portal",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 7. PM Vishwakarma Scheme
    {
        "name": "PM Vishwakarma Scheme",
        "short_name": "PM Vishwakarma",
        "short_description": "End-to-end support to traditional artisans and craftspeople including PM Vishwakarma Certificate, ID Card, skill training, toolkits, and collateral-free credit up to ₹3 Lakh.",
        "full_description": "PM Vishwakarma is a Central Sector Scheme to provide holistic end-to-end support to traditional artisans and craftspeople engaged in 18 traditional trades. Beneficiaries receive ₹15,000 toolkit incentive, skill training with ₹500/day stipend, and loans at concessional 5% interest rate.",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "department": "Ministry of MSME",
        "category": "Business",
        "sub_category": "Artisans & Craftsmen",
        "benefit": "₹15,000 toolkit stipend + Collateral-free loan up to ₹3,00,000 at 5% interest",
        "benefit_amount": "₹300,000",
        "launch_year": 2023,
        "status": "Active",
        "target_beneficiaries": "Artisans & Craftsmen in 18 traditional trades (Carpenters, Blacksmiths, Potters, Tailors, etc.)",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 70,
        "max_income": 10000000.0,
        "occupation_rules": ["Artisan", "Self Employed"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": [],
        "documents": ["Aadhaar Card", "Mobile Number linked with Aadhaar", "Bank Account Details", "Ration Card"],
        "application_steps": ["Visit Common Services Centre (CSC) or pmvishwakarma.gov.in", "Biometric authentication on CSC portal", "Gram Panchayat / ULB verification", "Approval by District Implementation Committee"],
        "official_source_url": "https://pmvishwakarma.gov.in/",
        "official_application_url": "https://pmvishwakarma.gov.in/Home/HowToApply",
        "source_name": "Ministry of MSME / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 8. PM SVANidhi Scheme
    {
        "name": "PM SVANidhi (Pradhan Mantri Street Vendor's AtmaNirbhar Nidhi)",
        "short_name": "PM SVANidhi",
        "short_description": "Micro-credit facility for street vendors providing working capital loans up to ₹50,000 with interest subsidy of 7% per annum.",
        "full_description": "PM SVANidhi is a Special Micro-Credit Facility for Street Vendors to facilitate working capital loans up to ₹10,000 (1st tranche), ₹20,000 (2nd tranche), and ₹50,000 (3rd tranche) with 7% interest subsidy on timely repayment and cashback on digital transactions.",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Housing and Urban Affairs",
        "department": "Department of Housing & Urban Affairs",
        "category": "Employment",
        "sub_category": "Street Vendors Micro Credit",
        "benefit": "Working capital loan up to ₹50,000 + 7% interest subsidy + digital cashback",
        "benefit_amount": "₹50,000",
        "launch_year": 2020,
        "status": "Active",
        "target_beneficiaries": "Urban and peri-urban street vendors",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 70,
        "max_income": 10000000.0,
        "occupation_rules": ["Street Vendor", "Self Employed"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": [],
        "documents": ["Vending Certificate / Identity Card issued by ULB", "Aadhaar Card", "Bank Account Details"],
        "application_steps": ["Visit pmsvanidhi.mohua.gov.in", "Check SRN / Vending Survey status", "Apply online or visit local bank branch"],
        "official_source_url": "https://pmsvanidhi.mohua.gov.in/",
        "official_application_url": "https://pmsvanidhi.mohua.gov.in/SchemeApplication",
        "source_name": "Ministry of Housing & Urban Affairs / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 9. PM Ujjwala Yojana 2.0
    {
        "name": "Pradhan Mantri Ujjwala Yojana 2.0 (PMUY)",
        "short_name": "PMUY 2.0",
        "short_description": "Free LPG gas connection along with first refill and stove to adult women from poor households.",
        "full_description": "Pradhan Mantri Ujjwala Yojana 2.0 provides deposit-free LPG connection to adult women from economically weaker households across India, including migrant households who can submit self-declaration for address proof.",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "department": "Oil Marketing Companies (IOCL/BPCL/HPCL)",
        "category": "Social Security",
        "sub_category": "Clean Fuel Energy",
        "benefit": "Free LPG Connection + First Refill + Stove (Hotplate)",
        "benefit_amount": "Free Connection & Refill",
        "launch_year": 2021,
        "status": "Active",
        "target_beneficiaries": "Adult women from BPL / SC / ST / EBC households",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 120,
        "max_income": 200000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": ["bpl"],
        "documents": ["Aadhaar Card of Applicant", "Ration Card / BPL Certificate", "Bank Account Details", "Address Proof or Self-Declaration"],
        "application_steps": ["Visit pmuy.gov.in or nearest LPG distributor (Indane/Bharatgas/HP)", "Submit Ujjwala application form with Aadhaar e-KYC", "Distributor inspects and installs free LPG connection"],
        "official_source_url": "https://www.pmuy.gov.in/",
        "official_application_url": "https://www.pmuy.gov.in/ujjwala2.html",
        "source_name": "Ministry of Petroleum & Natural Gas / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 10. Beti Bachao Beti Padhao & Sukanya Samriddhi Yojana
    {
        "name": "Sukanya Samriddhi Yojana (SSY)",
        "short_name": "SSY",
        "short_description": "Government small savings scheme for girl child offering high interest rate (8.2%) and tax deduction under Section 80C.",
        "full_description": "Sukanya Samriddhi Yojana is a small deposit scheme for the girl child launched under Beti Bachao Beti Padhao campaign. An account can be opened in the name of a girl child below 10 years of age with a minimum deposit of ₹250 per year.",
        "state": "All India",
        "scheme_type": "Central Sector",
        "government_level": "Central",
        "ministry": "Ministry of Women and Child Development",
        "department": "Department of Posts & Ministry of Finance",
        "category": "Women",
        "sub_category": "Girl Child Savings",
        "benefit": "8.2% p.a. guaranteed interest rate + Tax exemption under 80C",
        "benefit_amount": "Compounded Interest + Maturity Sum",
        "launch_year": 2015,
        "status": "Active",
        "target_beneficiaries": "Girl children up to 10 years of age",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 0,
        "max_age": 10,
        "max_income": 10000000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["Birth Certificate of Girl Child", "Aadhaar Card of Parent/Guardian", "Address Proof of Parent", "Passport Photograph"],
        "application_steps": ["Visit nearest Post Office or authorized commercial bank branch", "Fill Sukanya Samriddhi account opening form", "Deposit initial amount (Minimum ₹250)"],
        "official_source_url": "https://wcd.nic.in/bbbp-schemes",
        "official_application_url": "https://www.indiapost.gov.in/Financial/Pages/Content/Post-Office-Savings-Schemes.aspx",
        "source_name": "Department of Posts / WCD Ministry",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 11. Mukhyamantri Kanya Sumangala Yojana (Uttar Pradesh State Scheme)
    {
        "name": "Mukhyamantri Kanya Sumangala Yojana (Uttar Pradesh)",
        "short_name": "MKSY UP",
        "short_description": "Conditional cash transfer of ₹25,000 in six installments to girl children in Uttar Pradesh from birth up to higher education.",
        "full_description": "Mukhyamantri Kanya Sumangala Yojana is a flagship State Government scheme of Uttar Pradesh to ensure financial assistance to girls for health and education in 6 stages from birth to graduation/diploma.",
        "state": "Uttar Pradesh",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Department of Women and Child Development, UP",
        "department": "WCD Uttar Pradesh",
        "category": "Women",
        "sub_category": "Girl Child Education & Welfare",
        "benefit": "₹25,000 total financial incentive across 6 education milestones",
        "benefit_amount": "₹25,000",
        "launch_year": 2019,
        "status": "Active",
        "target_beneficiaries": "Girl children of Uttar Pradesh residents with annual family income up to ₹3 Lakh",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 0,
        "max_age": 25,
        "max_income": 300000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["Domicile Certificate of UP", "Income Certificate (Family income <= ₹3 Lakh)", "Birth Certificate of Girl Child", "Aadhaar Card of Parent", "Bank Passbook"],
        "application_steps": ["Visit mksy.up.gov.in", "Click on Citizen Service Portal Registration", "Fill online application and upload certificates", "Verification by District Probation Officer"],
        "official_source_url": "https://mksy.up.gov.in/",
        "official_application_url": "https://mksy.up.gov.in/women_welfare/citizen/guest_user_registration.php",
        "source_name": "Government of Uttar Pradesh / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 12. Ladli Laxmi Yojana 2.0 (Madhya Pradesh State Scheme)
    {
        "name": "Ladli Laxmi Yojana 2.0 (Madhya Pradesh)",
        "short_name": "Ladli Laxmi MP",
        "short_description": "Financial assurance and education incentives totaling over ₹1,43,000 for girl children in Madhya Pradesh.",
        "full_description": "Ladli Laxmi Yojana 2.0 is a comprehensive state welfare scheme of Madhya Pradesh to lay firm foundations for girl children by providing financial assistance at birth, school admission, and ₹25,000 college entrance grant.",
        "state": "Madhya Pradesh",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Department of Women and Child Development, MP",
        "department": "WCD Madhya Pradesh",
        "category": "Women",
        "sub_category": "Girl Child Welfare",
        "benefit": "Assurance bond + ₹25,000 college grant (Total benefit over ₹1.43 Lakh)",
        "benefit_amount": "₹143,000",
        "launch_year": 2007,
        "status": "Active",
        "target_beneficiaries": "Girl children born in MP to non-taxpayer parents",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 0,
        "max_age": 21,
        "max_income": 250000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["MP Domicile Certificate", "Birth Certificate", "Samagra ID", "Parent Income Certificate"],
        "application_steps": ["Apply via Anganwadi worker or online at ladlilaxmi.mp.gov.in", "Upload Samagra ID and Birth Certificate", "Approval by Project Officer"],
        "official_source_url": "https://ladlilaxmi.mp.gov.in/",
        "official_application_url": "https://ladlilaxmi.mp.gov.in/",
        "source_name": "Government of Madhya Pradesh",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 13. Gruha Lakshmi Scheme (Karnataka State Scheme)
    {
        "name": "Gruha Lakshmi Scheme (Karnataka)",
        "short_name": "Gruha Lakshmi KA",
        "short_description": "Monthly financial assistance of ₹2,000 to the female head of every eligible household in Karnataka.",
        "full_description": "Gruha Lakshmi Scheme is one of the five guarantee schemes of the Karnataka State Government, providing direct benefit transfer of ₹2,000 per month to women who are designated as heads of households in Ration Cards (BPL / APL).",
        "state": "Karnataka",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Department of Women and Child Development, Karnataka",
        "department": "WCD Karnataka",
        "category": "Women",
        "sub_category": "Household Income Support",
        "benefit": "₹2,000 / month direct bank transfer",
        "benefit_amount": "₹24,000 / year",
        "launch_year": 2023,
        "status": "Active",
        "target_beneficiaries": "Women household heads in Karnataka holding Ration Cards",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 120,
        "max_income": 300000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["Aadhaar Card", "Ration Card (BPL/APL/Antyodaya)", "Aadhaar-seeded Bank Account Details"],
        "application_steps": ["Visit Seva Sindhu portal (sevasindhugs.karnataka.gov.in) or Karnataka One centre", "Authenticate Aadhaar", "Submit application"],
        "official_source_url": "https://sevasindhugs.karnataka.gov.in/",
        "official_application_url": "https://sevasindhugs.karnataka.gov.in/Gruhalakshmi/",
        "source_name": "Government of Karnataka / Seva Sindhu",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 14. Magalir Urimai Thogai Scheme (Tamil Nadu State Scheme)
    {
        "name": "Kalaignar Magalir Urimai Thogai Scheme (Tamil Nadu)",
        "short_name": "Magalir Urimai TN",
        "short_description": "Monthly rights grant of ₹1,000 to eligible women heads of households across Tamil Nadu.",
        "full_description": "Kalaignar Magalir Urimai Thogai Scheme is a flagship social welfare programme of Tamil Nadu Government providing a monthly financial aid of ₹1,000 to adult women heads of eligible families.",
        "state": "Tamil Nadu",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Special Programme Implementation Department, Tamil Nadu",
        "department": "Government of Tamil Nadu",
        "category": "Women",
        "sub_category": "Women Financial Empowerment",
        "benefit": "₹1,000 / month direct cash transfer",
        "benefit_amount": "₹12,000 / year",
        "launch_year": 2023,
        "status": "Active",
        "target_beneficiaries": "Women heads of families in TN with annual family income under ₹2.5 Lakh",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 21,
        "max_age": 120,
        "max_income": 250000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["Smart Family Card (Ration Card)", "Aadhaar Card", "Electricity Consumer Number", "Aadhaar-linked Bank Account"],
        "application_steps": ["Camp held at local Fair Price Shop (Ration Shop)", "Submit token form with biometric Aadhaar verification", "Status sent via SMS"],
        "official_source_url": "https://kmut.tn.gov.in/",
        "official_application_url": "https://kmut.tn.gov.in/",
        "source_name": "Government of Tamil Nadu",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 15. Rythu Bandhu / Rythu Bharosa (Telangana & AP State Schemes)
    {
        "name": "Rythu Bharosa Scheme (Andhra Pradesh)",
        "short_name": "Rythu Bharosa AP",
        "short_description": "Annual financial assistance of ₹13,500 per farmer family in Andhra Pradesh for agricultural operational costs.",
        "full_description": "YSR Rythu Bharosa - PM Kisan is a State Government scheme of Andhra Pradesh providing financial assistance of ₹13,500 per year to farmer families including tenant farmers belonging to SC, ST, BC, and Minority categories.",
        "state": "Andhra Pradesh",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Department of Agriculture, Andhra Pradesh",
        "department": "Agriculture Department AP",
        "category": "Farmers",
        "sub_category": "Farmer Direct Benefit Transfer",
        "benefit": "₹13,500 / year per farmer family",
        "benefit_amount": "₹13,500",
        "launch_year": 2019,
        "status": "Active",
        "target_beneficiaries": "Landowning and tenant farmers in Andhra Pradesh",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 18,
        "max_age": 120,
        "max_income": 1000000.0,
        "occupation_rules": ["Farmer"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": ["farmer"],
        "documents": ["Pattadar Passbook / Land Record", "Aadhaar Card", "Bank Account Number", "CCORC (Crop Cultivator Rights Certificate for Tenants)"],
        "application_steps": ["Verify name in Village Secretariat (Rythu Bharosa Kendra)", "Submit land pattadar and bank details", "Field verification by Agricultural Extension Officer"],
        "official_source_url": "https://ysrrythubharosa.ap.gov.in/",
        "official_application_url": "https://ysrrythubharosa.ap.gov.in/",
        "source_name": "Government of Andhra Pradesh",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 16. Kanyashree Prakalpa (West Bengal State Scheme)
    {
        "name": "Kanyashree Prakalpa (West Bengal)",
        "short_name": "Kanyashree WB",
        "short_description": "Annual scholarship of ₹1,000 (K1) and one-time grant of ₹25,000 (K2) to unmarried girl students in West Bengal to prevent child marriage.",
        "full_description": "Kanyashree Prakalpa is an award-winning conditional cash transfer scheme aimed at improving the status and wellbeing of the girl child in West Bengal by incentivizing school education and delaying marriage until age 18.",
        "state": "West Bengal",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Department of Women & Child Development and Social Welfare, West Bengal",
        "department": "WCD West Bengal",
        "category": "Students",
        "sub_category": "Girl Child Education Scholarship",
        "benefit": "Annual scholarship of ₹1,000 + One-time grant of ₹25,000 at age 18",
        "benefit_amount": "₹26,000",
        "launch_year": 2013,
        "status": "Active",
        "target_beneficiaries": "Unmarried girls aged 13-19 enrolled in school/college in West Bengal",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 13,
        "max_age": 19,
        "max_income": 120000.0,
        "occupation_rules": ["Student"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": ["student"],
        "documents": ["Unmarried Status Self-Declaration", "School Enrollment Certificate", "Bank Account in Girl's Name", "Aadhaar / Birth Certificate"],
        "application_steps": ["Collect Kanyashree application form from school / college Headmaster", "Fill K1 (annual) or K2 (one-time) form", "Headmaster uploads form on wbkanyashree.gov.in portal"],
        "official_source_url": "https://wbkanyashree.gov.in/",
        "official_application_url": "https://wbkanyashree.gov.in/",
        "source_name": "Government of West Bengal / myScheme",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 17. Mukhyamantri Chiranjeevi Swasthya Bima Yojana (Rajasthan)
    {
        "name": "Mukhyamantri Chiranjeevi Swasthya Bima Yojana (Rajasthan)",
        "short_name": "Chiranjeevi Rajasthan",
        "short_description": "Cashless health insurance cover up to ₹25 Lakh per family per year for all residents of Rajasthan.",
        "full_description": "Mukhyamantri Chiranjeevi Swasthya Bima Yojana provides universal health coverage up to ₹25 Lakh per family per year for inpatient medical treatment across government and empanelled private hospitals in Rajasthan.",
        "state": "Rajasthan",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Medical, Health and Family Welfare Department, Rajasthan",
        "department": "State Health Agency Rajasthan",
        "category": "Health",
        "sub_category": "Universal Health Insurance",
        "benefit": "Cashless health insurance up to ₹25,00,000 per family per year",
        "benefit_amount": "₹2,500,000",
        "launch_year": 2021,
        "status": "Active",
        "target_beneficiaries": "All families holding Jan Aadhar card in Rajasthan",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 0,
        "max_age": 120,
        "max_income": 10000000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": [],
        "documents": ["Jan Aadhar Card", "Aadhaar Card", "Mobile Number"],
        "application_steps": ["Visit chiranjeevi.rajasthan.gov.in or E-Mitra kiosk", "Authenticate Jan Aadhar card", "Free registration for NFSA / SECC / Small Farmers; nominal premium for others"],
        "official_source_url": "https://chiranjeevi.rajasthan.gov.in/",
        "official_application_url": "https://chiranjeevi.rajasthan.gov.in/",
        "source_name": "Government of Rajasthan",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 18. Delhi Free Bus Travel for Women (Rajiv Gandhi Yatri Scheme / Pink Pass)
    {
        "name": "Delhi Free Bus Travel Scheme for Women (Pink Pass)",
        "short_name": "Delhi Pink Pass",
        "short_description": "100% free bus travel in DTC and DIMTS AC & Non-AC buses for all female commuters in Delhi.",
        "full_description": "The Government of NCT of Delhi provides zero-ticket (Pink Pass) free bus travel for all female passengers travelling on Delhi Transport Corporation (DTC) and Cluster (DIMTS) buses across the National Capital Territory of Delhi.",
        "state": "Delhi",
        "scheme_type": "Union Territory",
        "government_level": "Union Territory",
        "ministry": "Transport Department, Government of NCT of Delhi",
        "department": "Delhi Transport Corporation (DTC)",
        "category": "Social Security",
        "sub_category": "Public Transport Subsidy",
        "benefit": "100% Free Bus Travel in all DTC and DIMTS buses in Delhi",
        "benefit_amount": "100% Fare Waiver",
        "launch_year": 2019,
        "status": "Active",
        "target_beneficiaries": "All women and girl commuters travelling in Delhi",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 0,
        "max_age": 120,
        "max_income": 10000000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["None required onboard (Conductor issues Pink Pass ticket)"],
        "application_steps": ["Board any DTC or DIMTS bus in Delhi", "Ask bus conductor for Pink Pass", "No fee or ID verification required"],
        "official_source_url": "https://transport.delhi.gov.in/",
        "official_application_url": "https://dtc.delhi.gov.in/",
        "source_name": "Government of NCT of Delhi / DTC",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 19. Majhi Ladki Bahin Yojana (Maharashtra State Scheme)
    {
        "name": "Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)",
        "short_name": "Ladki Bahin MH",
        "short_description": "Monthly financial aid of ₹1,500 to women aged 21-65 years in Maharashtra.",
        "full_description": "Mukhyamantri Majhi Ladki Bahin Yojana is a major social assistance scheme launched by the Government of Maharashtra to provide direct monthly financial support of ₹1,500 to adult married, widowed, divorced, or single women.",
        "state": "Maharashtra",
        "scheme_type": "State Government",
        "government_level": "State",
        "ministry": "Women and Child Development Department, Maharashtra",
        "department": "WCD Maharashtra",
        "category": "Women",
        "sub_category": "Women Financial Support",
        "benefit": "₹1,500 / month direct benefit transfer",
        "benefit_amount": "₹18,000 / year",
        "launch_year": 2024,
        "status": "Active",
        "target_beneficiaries": "Women aged 21 to 65 years residing in Maharashtra with annual income under ₹2.5 Lakh",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 21,
        "max_age": 65,
        "max_income": 250000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Female"],
        "special_conditions": [],
        "documents": ["Aadhaar Card", "Maharashtra Domicile Certificate / Ration Card", "Annual Income Certificate (<= ₹2.5 Lakh)", "Bank Passbook"],
        "application_steps": ["Apply via 'Nari Shakti Doot' mobile application or Anganwadi center", "Fill personal and bank details", "Submit e-KYC verification"],
        "official_source_url": "https://ladkibahin.maharashtra.gov.in/",
        "official_application_url": "https://ladkibahin.maharashtra.gov.in/",
        "source_name": "Government of Maharashtra",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    },
    # 20. National Social Assistance Programme (NSAP - Indira Gandhi National Old Age Pension)
    {
        "name": "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
        "short_name": "IGNOAPS - NSAP",
        "short_description": "Monthly pension for BPL senior citizens aged 60 years and above under the National Social Assistance Programme.",
        "full_description": "IGNOAPS is a core Centrally Sponsored Scheme under NSAP providing monthly social security pension to elderly citizens living below the poverty line (BPL).",
        "state": "All India",
        "scheme_type": "Centrally Sponsored",
        "government_level": "Central",
        "ministry": "Ministry of Rural Development",
        "department": "NSAP Division",
        "category": "Pension",
        "sub_category": "Old Age Social Security Pension",
        "benefit": "Monthly pension of ₹400 to ₹1,000 (Central + State contribution)",
        "benefit_amount": "Monthly Pension",
        "launch_year": 1995,
        "status": "Active",
        "target_beneficiaries": "Senior citizens aged 60+ belonging to BPL households",
        "eligibility_mode": "DETERMINISTIC",
        "min_age": 60,
        "max_age": 120,
        "max_income": 120000.0,
        "occupation_rules": ["All"],
        "category_rules": ["All"],
        "gender_rules": ["Any"],
        "special_conditions": ["senior_citizen", "bpl"],
        "documents": ["Aadhaar Card", "BPL Ration Card", "Age Proof Certificate", "Bank Account Details"],
        "application_steps": ["Submit application at Block Development Office (BDO) / Gram Panchayat / Tehsildar office", "Physical verification by Social Welfare Inspector", "Sanction letter issued"],
        "official_source_url": "https://nsap.nic.in/",
        "official_application_url": "https://nsap.nic.in/nsap/DirectApply.do",
        "source_name": "Ministry of Rural Development / NSAP Portal",
        "last_verified_at": "2026-08-20",
        "verification_status": "VERIFIED"
    }
]
